### ISSUE TITLE
/api/v3/channel/update 导致频道崩溃

### ISSUE THREAD

**Issue by DancingSnow0517** [kaiheila/api-docs#113]
### 如何复现问题?
/api/v3/channel/update
channel_id = 4121189805803798
name = test

### 你希望的输出是什么?
正确修改频道名字
### 你得到什么结果?
客户端打开频道无限崩溃
![image](https://user-images.githubusercontent.com/60736156/167285346-eb050ae3-0847-4c3c-b822-756bf1115a84.png)

### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      |  python
| 你的操作系统      |  windows

**Comment by QRrui** [comment]
从你的传参来看，应该不是这个接口操作引起的，当时调用此接口不会对频道做任何修改。请问此前你是否修改了slow_mode？

**Comment by QRrui** [comment]
从你的传参来看，应该不是这个接口操作引起的，当时调用此接口不会对频道做任何修改。请问此前你是否修改了slow_mode？

**Comment by DancingSnow0517** [comment]
> 

啊，是的之前试过传`slow_mode`，但是没有效果，然后就去传别的参数就出错了
