### ISSUE TITLE
根据用户id和服务器id获取用户所在语音频道 输出错误

### ISSUE THREAD

**Issue by shuyangzhang** [kaiheila/api-docs#115]
### 如何复现问题?
+ 接口地址 `/api/v3/channel-user/get-joined-channel` 
+ 文档地址 [接口文档](https://developer.kaiheila.cn/doc/http/channel-user#%E6%A0%B9%E6%8D%AE%E7%94%A8%E6%88%B7id%E5%92%8C%E6%9C%8D%E5%8A%A1%E5%99%A8id%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E6%89%80%E5%9C%A8%E8%AF%AD%E9%9F%B3%E9%A2%91%E9%81%93)
+ 问题描述：
如果从服务器A的语音频道a离开后，第一次进入服务器B的任意语音频道b后，该接口不能正确返回频道b的id，返回为空
+ 复现方法：
先进入另外一个服务器A的语音频道，再进入测试用服务器B的任意语音频道b1，此时调用接口即可复现，如果离开b1重新进入b1，则接口可以正常返回；如果离开b1，进入任意一个服务器B的其他语音频道b2，该接口亦可以正常返回；问题仅发生在第一次切换服务器的语音频道时

### 其他信息
+ 语言 Python
+ 操作系统 macos12.4 arm64(apple/m1)

**Comment by buptlsp** [comment]
已经fix
