### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by DeeChael** [kaiheila/api-docs#134]
### 功能模块
客户端识别用户正在播放的音乐

### 你希望的功能描述？
支持识别[Spotify](https://www.spotify.com)播放的音乐

### 功能的主要使用产景？
可以识别用户使用Spotify播放的歌曲
并且给https://developer.kookapp.cn/doc/http/game#%E6%B7%BB%E5%8A%A0%E6%B8%B8%E6%88%8F/%E9%9F%B3%E4%B9%90%E8%AE%B0%E5%BD%95-%E5%BC%80%E5%A7%8B%E7%8E%A9/%E5%90%AC
音乐软件枚举中添加spotify

### 其它信息
无

**Comment by Aewait** [comment]
这不是有嘛
![image](https://user-images.githubusercontent.com/87506951/179390514-cd55abb8-6d05-4891-a785-9d883efd7f2f.png)

**Comment by DeeChael** [comment]
> 这不是有嘛 ![image](https://user-images.githubusercontent.com/87506951/179390514-cd55abb8-6d05-4891-a785-9d883efd7f2f.png)
> 
> 注：这不是我自己的，我在频道里看到的别人的截图

这个是伴奏功能，这个截图也是我截的，慕雪，看看我ID

**Comment by DeeChael** [comment]
![image](https://user-images.githubusercontent.com/63186003/179432765-20e3b076-3ea5-447c-8f15-005cdb53387a.png)
![image](https://user-images.githubusercontent.com/63186003/179432806-191844de-2b9a-422e-8dce-ca2205e02546.png)
![image](https://user-images.githubusercontent.com/63186003/179432817-3027327f-e6d1-4b6a-a6e1-c621a491931c.png)

**Comment by Aewait** [comment]
哦，我知道了，你想识别出音乐然后显示动态对吧

**Comment by buptlsp** [comment]
活动中心 在玩游戏识别
