### ISSUE TITLE
Oauth2的获取的code无法获取accesstoken，一直说过期

### ISSUE THREAD

**Issue by wushiwuwendong2** [kaiheila/api-docs#141]
### 如何复现问题?
请给出api接口，并给出相应的调用步骤
调用/api/oauth2/token
获得了code
利用code根据文档参数调用/api/oauth2/token
发送请求之后给出的结果是
![image](https://user-images.githubusercontent.com/65708063/181919125-671c209b-3838-4ec6-acfb-e21cbc7697f3.png)
![image](https://user-images.githubusercontent.com/65708063/181919111-f8209be1-bfa8-458f-8a94-3ec8565e0660.png)

{
    "code": 400,
    "message": "Authorization code doesn't exist or is invalid for the client",
    "data": {
        "name": "Bad Request",
        "status": 400
    }
}
### 你希望的输出是什么?
我希望输出正确的access_token
### 你得到什么结果?

我希望输出正确的access_token
### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      | php
| 你的操作系统      | ubuntu

**Comment by Tongzzzzz** [comment]
query string中存在两个参数, 一个 `code`, 一个 `state`, 可以检查下 `code` 参数是否取值正确
