### ISSUE TITLE
API BUG反馈 获取文件消息时收到的类型为卡片

### ISSUE THREAD

**Issue by naimen** [kaiheila/api-docs#149]
### 如何复现问题?
请给出api接口，并给出相应的调用步骤
针对一个只含文件的消息使用
`/api/v3/message/view`

### 你希望的输出是什么?
``` 
{ ...,
    data: {
        "type": 4,
        "attachments": {...},
        ...
    }
}
```
### 你得到什么结果?
```
{ ...,
    data: {
        "type": 10,
        "attachments": null,
        ...
    }
}
```
### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      |  python -- khl.py
| 你的操作系统      | Linux

**Comment by gehongyan** [comment]
开发者社区回复说是已经将文件消息统一转成卡片消息形式承载内容了

**Comment by buptlsp** [comment]
文件消息后续将成为历史
