### ISSUE TITLE
消息技术实现

### ISSUE THREAD

**Issue by fronEnd-test** [kaiheila/api-docs#167]
语音对讲技术实现，你好，请问你们语音对讲是用什么编码的？我最近也在研究语音对讲，技术上遇到点难题，
vue作为技术框架，websocket作为通信方式，实时语音读取，pcm格式文件，打算编码未opus格式
希望能帮忙解答下，语音采集多久时间发送到服务器最好，pcm编码opus如何变码，麻烦解答下，谢谢

**Comment by buptlsp** [comment]
建议先了解下webrtc
