### ISSUE TITLE
/user/me 字段类型错误

### ISSUE THREAD

**Issue by abrahum** [kaiheila/api-docs#169]
### 如何复现问题?

调用 /user/me api

### 你希望的输出是什么?

根据文档，invited_count 字段返回类型为 int

具有 mobile_verify: bool 字段

### 你得到什么结果?

实际收到类型为 String

缺失 mobile_verify 字段

### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      |  Rust
| 你的操作系统      |  windows/Linux

**Comment by etby** [comment]
@abrahum mobile_verify 字段是没有，应该是 mobile_verified。
参考：https://developer.kookapp.cn/doc/objects#%E7%94%A8%E6%88%B7%20User

**Comment by etby** [comment]
@abrahum invited_count 的格式目前应该是 int 了
