### ISSUE TITLE
bug report: challenge 和 events 使用的压缩方式不一样

### ISSUE THREAD

**Issue by TWT233** [kaiheila/api-docs#2]
因为没有 template 所以简单写一下：

开启 compress 时，challenge 使用 deflate 方式压缩， 但 events 使用 zlib 方式压缩

下午和 tttzzz 沟通过了，如果已经 fix 的话直接 close 该 issue 即可，谢谢！

**Comment by buptlsp** [comment]
已经处理，感谢反馈
