### ISSUE TITLE
没有获取途径的情况下点击获取语音，会陷入死循环

### ISSUE THREAD

**Issue by Makarov3212** [kaiheila/api-docs#201]
### 如何复现问题?
在编辑个人资料的页面点击更改入场语音，如果这个语音已经绝版，没有获取途径，就会卡住一直转圈，没有任何按钮可以点击返回上一个界面，只能重启

![image](https://github.com/kaiheila/api-docs/assets/30566176/036d4d23-4cf2-4adf-a6db-ba9a2e5310fa)

![image](https://github.com/kaiheila/api-docs/assets/30566176/c71496c8-9f0e-444e-8043-180d79e37583)

### 你希望的输出是什么?
无

### 你得到什么结果?
我希望能够正常使用，没有途径就给我弹回上一个界面

### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      |  无
| 你的操作系统      |  windows

**Comment by burningtnt** [comment]
这不是 API 文档相关的问题。请关闭本 Issue，至软件右上角提工单反馈
