### ISSUE TITLE
关于禁止 OBS 直播

### ISSUE THREAD

**Issue by MnFeN** [kaiheila/api-docs#208]
你们软件项目主管是脑残么？不知道你们软件主流玩家是玩游戏的么？

不知道玩游戏的有多少开 OBS 么？OBS 是否在直播都不会默认检测么？

别人直播的时候开启自由麦是自己选择承担的风险，用得着你来狗拿耗子管闲事？

论语音质量差的一逼，论视频分享挤不出来那点网速，时间拿来干什么了？做你那个逼小游戏？

这还配对标 discord？你连 discord 一根毛都比不上

每次打开强制更新是你们急着去给亲人上坟么？不会退出的时候更新？

就这还嫌凉的不够快，身边玩游戏的都换软件了，祝你们**早日好死**

**Comment by buptlsp** [comment]
看得出你很愤怒，作为平台方，只能对你说声抱歉。
你知道这样会让KOOK死的很快，我们也知道，但是不这么做，可能会死的更快。在早日好死之前，请还是要允许我们挣扎一下，虽然这样可能会让你们很愤怒。
人类的悲欢并不相同，希望你能在新的平台找回玩游戏的快乐，希望KOOK还能活着，希望大家还有相逢的一天。

**Comment by MnFeN** [comment]
> “早日好死之前，请还是要允许我们挣扎一下，虽然这样可能会让你们很愤怒。”

不用跟用户卖惨，不管是你平台需要有盈利项目还是真敏感时期上面有规定，也不是你们做缩头乌龟发个消息敷衍了事的理由。

连更新日志都不写明白，官方反馈服务器里面对那么多用户的质疑连个屁都不放。你们对得起用户付的费吗？对得起早期用户主动给你们做的宣传吗？
