### ISSUE TITLE
[bug] Unlaughed promise when addBlockList

### ISSUE THREAD

**Issue by sam01101** [kaiheila/api-docs#43]
**Describe the bug**
>Unlaughed promise when addBlockList

如题.

**To Reproduce**
- 随机找个人
- 移除并加入黑名单
- 按取消

**Expected behavior**
- Promise should return normal

**Screenshots**
![image](https://img.kaiheila.cn/assets/2021-03/GRrelwmgQd0ik0b4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Desktop app

**Comment by buptlsp** [comment]
感谢反馈，后续修复

**Comment by buptlsp** [comment]
fixed, thx
