### ISSUE TITLE
给 Webhook 回调请求加上 Header Content-Encoding: deflate

### ISSUE THREAD

**Issue by yehzhang** [kaiheila/api-docs#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yehzhang** [comment]
oops 回复按得太快了……

Describe the bug
所有机器人 Webhook 回调请求都是 deflate 压缩过的，需要手动解压。这给开发者带来了困扰，因为他们一般都不需要去关心压缩，框架都会自动解压好，但框架需要在 Headers 中看见 Content-Encoding: deflate 才会自动解压。加这个 Header 也是发送压缩过的 HTTP 请求的常规操作。

**Comment by yehzhang** [comment]
我甚至看见有些人不知道怎么让框架解压，干脆就 compress=0 关闭了压缩

**Comment by Tongzzzzz** [comment]
这个问题我们之前考虑过, 但是尝试后发现某些语言和框架并不能识别这个header参数且有些会报错, 所以为了兼顾这些特殊的问题, 暂时应该不会增加该参数.

**Comment by Afanyiyu** [comment]
……当时也说过 那就也加一个query或者类似的参数来控制这个行为就解决了
这说到底也是个别框架的问题，不应该因为个别框架就去掉符合通用规定的标识

**Comment by yehzhang** [comment]
加这个 header 的话少部分框架报错，不加的话所有框架都会因为无法自动解压而报错？开发者配置 Callback URL 上来就要 debug 两小时，这体验可以变得更好

**Comment by yehzhang** [comment]
如果想兼容少部分框架的话，可以让它们用 compress=0，然后给 compress=1 的请求加 Header
