### ISSUE TITLE
/api/v3/message/list?flag=around 需要半分钟

### ISSUE THREAD

**Issue by yehzhang** [kaiheila/api-docs#46]
**Describe the bug**
比如这个请求[1]。它只返回二十条消息，却要半分多钟，不适合生产使用。用其它 flag 参数的话则没有问题。

[1]: http://kaiheila.cn/api/v3/message/list?flag=around&target_id=1071036821430777&msg_id=48940efa-9295-4c7f-a159-7f97343a04ee（需要 Authorization）

**Comment by Quatrecentquatre-404** [comment]
I'm agree with this idea. I was surprise the first time I used this route to access to a message. It took so long.

**Comment by buptlsp** [comment]
I have fixed this problem. thanks for issue.
