### ISSUE TITLE
/api/v3/message/reaction-list returns stale data

### ISSUE THREAD

**Issue by yehzhang** [kaiheila/api-docs#53]
**To Reproduce**
1. 使用 Webhook 监听 added_reaction 事件
2. 当事件发生时使用事件的 msg_id 请求 /api/v3/message/reaction-list

**Expected behavior**
API 返回所有该消息的回应。

**Actual behavior**
API 返回的回应中不包含 added_reaction 事件所指的回应。十次中大概发生一次。

**Comment by buptlsp** [comment]
这个并不一定有。因为用户点击可点是先点下reaction, 然后再点击取消。等到你接收到added_reaction事件，列表中并不一定存在该回应，这个是正常的，这个是你实现逻辑的问题。
