### ISSUE TITLE
添加获取用户信息的 API

### ISSUE THREAD

**Issue by yehzhang** [kaiheila/api-docs#54]
我的机器人需要对用户的消息回应做出反应，并且获得该用户的名称。有没有 API 能够通过用户 id 获取用户名？

现在的做法是收取 Webhook 的 added_reaction 事件，然后通过事件的 msg_id 查询该消息下所有回应，包括事件所指的回应及用户名，但会遇到问题 #53。

**Comment by buptlsp** [comment]
1. 推荐的做法应该是要缓存用户的信息。然后通过事件来更新。
2.  /api/v3/user/view?guild_id=xxx&user_id=xxx， 这个接口可能是你想要的
