### ISSUE TITLE
Unexpected nickname in text message event

### ISSUE THREAD

**Issue by yehzhang** [kaiheila/api-docs#55]
**To Reproduce**
用 Webhook 接受任意带有文字消息的事件 （https://developer.kaiheila.cn/doc/event/message）

**Expected behavior**
nickname 属性是用户的服务器昵称。

**Actual behavior**
nickname 属性是用户名，和 username 一样。

**Comment by buptlsp** [comment]
如果用户在服务器中没有设置nickname, nickname=username.
如果用户有设置nickname, nickname!=username.
