### ISSUE TITLE
[建议] 为issue提供更友善的issue模板

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#57]
我个人认为应当将issue作为主要的bug反馈区而不是那个 问题反馈 的频道。
站在我个人的角度，希望能为issue提供更清晰的模板，而不是github给的默认模板，并将反馈上报的重心转移到这边儿，因为在这里，能够更好的追踪问题进度、查询问题历史记录、讨论、问题之间的关联与分类等

以上是我个人建议🐱

**Comment by buptlsp** [comment]
你希望的issue模板是什么样子呢?有示例么？

**Comment by ForteScarlet** [comment]
比如说有“文档内容反馈”、“api反馈”、“建议意见” 之类的，
示例的话，我个人的可以参考下：https://github.com/ForteScarlet/simpler-robot/issues/new/choose
其他的大型开源框架可以参考：
- [mybatis-plus](https://github.com/baomidou/mybatis-plus/issues/new) (只有一个模板，存在注释说明)
- [spring-boot](https://github.com/spring-projects/spring-boot/issues/new) (只有一个模板，存在注释说明)
- [vue](https://github.com/vuejs/vue/issues/new/choose) (多个模板)
- [react](https://github.com/facebook/react/issues/new/choose) (多个模板)
- [yii](https://github.com/yiisoft/yii2/issues/new) (只有一个模板，存在注释说明)

**Comment by buptlsp** [comment]
已处理
