### ISSUE TITLE
开黑啦官方的吐槽中心链接过期

### ISSUE THREAD

**Issue by fqh333** [kaiheila/api-docs#58]
开黑啦官方的吐槽中心链接 好像过期了 有没有新的链接啊
想弄一下bot玩玩 但是好像需要先申请
谢谢了

**Comment by buptlsp** [comment]
直接在发现页，第一个就是吐槽中心，直接加进去就好了

**Comment by nuoxd** [comment]
发现页未找到吐槽中心

**Comment by buptlsp** [comment]
https://kaihei.co/ZhNFAg    这个是邀请链接，可以通过这个进入吧
