### ISSUE TITLE
语音邀请链接仅可使用type为1的消息

### ISSUE THREAD

**Issue by fi6** [kaiheila/api-docs#59]
###  功能模块
使用kmarkdown+链接生成的链接只能打开网页版，不能在当前客户端加入语音频道

###  你希望的功能描述？
希望可以使用其他type的消息邀请玩家加入语音频道（或者增加按钮功能，使按钮可以加入语音频道）

### 功能的主要使用产景？
组队bot，创建房间后需要邀请玩家加入语音频道，如果是采用临时更新card message作为菜单的形式，反复发送type为1的临时消息会导致菜单被刷没，只能刷新频道消息。

### 其它信息
无

**Comment by buptlsp** [comment]
这个功能我们考虑一下。
