### ISSUE TITLE
Typo: docs -> doc

### ISSUE THREAD

**Issue by Afanyiyu** [kaiheila/api-docs#6]
https://developer.kaiheila.cn/doc/reference

`速度限制` Section

有关速度限制的问题，请参阅速率限制一节 (https://developer.kaiheila.cn/docs/rate-limit)

https://developer.kaiheila.cn/docs/rate-limit (404)
->
https://developer.kaiheila.cn/doc/rate-limit

**Comment by buptlsp** [comment]
已处理，感谢反馈
