### ISSUE TITLE
临时更新消息时如果消息超过一个月会导致按钮不可用

### ISSUE THREAD

**Issue by fi6** [kaiheila/api-docs#60]
### 如何复现问题?
api/message/update接口，提供temp_target_id时，如果消息类型为10，消息本身时长超过一个月，且更新的消息中含有按钮，会导致按钮不可用（消息不存在或你没有权限操作）

### 你希望的输出是什么?
正常更新

### 你得到什么结果?
消息不存在或你没有权限操作

### 其它信息
无

**Comment by buptlsp** [comment]
这个就是这么设计的，临时消息本来就只能做为临时的提醒，时间过长将不可用。
而且用户一旦刷新或者重连，都会丢失临时消息，所以请不要用临时消息来做长期的功能。
