### ISSUE TITLE
UserChat的 List 与 View 中返回值数据字段 target_info 的内容差异问题

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#61]
### 文档的具体地址?
<https://developer.kaiheila.cn/doc/http/user-chat#%E8%8E%B7%E5%8F%96%E7%A7%81%E4%BF%A1%E8%81%8A%E5%A4%A9%E4%BC%9A%E8%AF%9D%E5%88%97%E8%A1%A8>

<https://developer.kaiheila.cn/doc/http/user-chat#%E8%8E%B7%E5%8F%96%E7%A7%81%E4%BF%A1%E8%81%8A%E5%A4%A9%E4%BC%9A%E8%AF%9D%E8%AF%A6%E6%83%85>

### 你认为有问题的文档内容
在`List`中，存在 `target_info - online` 字段，但是在`View`中则没有：
![](https://img.kaiheila.cn/assets/2021-08/4yU2hkmsim1cc0n9.png)
![](https://img.kaiheila.cn/assets/2021-08/YVc48pcucB18k0le.png)

那么这两个中的targetInfo是不同的吗（就是是存在online字段的差异的吗）

**Comment by Bin8ge** [comment]
文档漏掉了， target_info 是一样的

**Comment by Tongzzzzz** [comment]
fixed, https://github.com/kaiheila/api-docs/pull/67
