### ISSUE TITLE
希望对接口中的“时间”性质的字段追加说明

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#62]
###  功能模块
文档中与 **时间(戳)** 相关内容

###  你希望的功能描述？
针对于文档中一些与时间相关的描述（例如 [获取私信聊天会话列表](https://developer.kaiheila.cn/doc/http/user-chat#%E8%8E%B7%E5%8F%96%E7%A7%81%E4%BF%A1%E8%81%8A%E5%A4%A9%E4%BC%9A%E8%AF%9D%E8%AF%A6%E6%83%85) 中的 `last_read_time`、`latest_msg_time` 等 ）进行一个描述，表述他的时间格式是秒还是毫秒，或者在一个统一的地方对时间格式进行概述，比如在 [资源 - 参考](https://developer.kaiheila.cn/doc/reference) 中追加一个对全局时间格式的描述。

**Comment by Bin8ge** [comment]
文档更新 会增加描述

**Comment by Tongzzzzz** [comment]
fixed, https://github.com/kaiheila/api-docs/pull/67
