### ISSUE TITLE
对消息内容中 attachments、quote 的字段疑问

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#64]
### 文档的具体地址?
https://developer.kaiheila.cn/doc/http/message

### 你认为有问题的文档内容
在消息详情数据中， `attachments`、`quote` 这两个字段的格式并没有进行描述，且在示例数据中也都是以 `[]` 和 `null` 略过了。

**Comment by Bin8ge** [comment]
更新文档，问会增加示例及描述

**Comment by Tongzzzzz** [comment]
fixed, https://github.com/kaiheila/api-docs/pull/67
