### ISSUE TITLE
消息详情中 mention_here 字段的类型描述与示例不符

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#65]
### 文档的具体地址?
https://developer.kaiheila.cn/doc/http/message

### 你认为有问题的文档内容
在描述中，它被标记为 `boolean` 类型：
![image](https://user-images.githubusercontent.com/40045247/127975457-8ed926c4-e7e5-4adf-ae90-7a81f266e65e.png)

但在返回示例中却表现为了数组格式：
![image](https://user-images.githubusercontent.com/40045247/127975540-6d59ff4d-b4bf-4b11-89f6-52a3b8879fee.png)

**Comment by Bin8ge** [comment]
后续更新文档，会修改

**Comment by Tongzzzzz** [comment]
fixed, https://github.com/kaiheila/api-docs/pull/67
