### ISSUE TITLE
获取当前用户信息接口中没有system字段

### ISSUE THREAD

**Issue by ForteScarlet** [kaiheila/api-docs#66]
### 文档的具体地址?
https://developer.kaiheila.cn/doc/http/user#%E8%8E%B7%E5%8F%96%E5%BD%93%E5%89%8D%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF

### 你认为有问题的文档内容
文档的字段说明中说存在一个 `system` 字段：
![image](https://user-images.githubusercontent.com/40045247/128028897-a60a48e1-3faa-44e8-83eb-4f325ab119b8.png)

但是似乎实际上并没有这个字段。

**Comment by Bin8ge** [comment]
这个字段文档多写了，后续会去掉

**Comment by Tongzzzzz** [comment]
fixed, https://github.com/kaiheila/api-docs/pull/67
