### ISSUE TITLE
使用错误的 Autherization 返回的 code 不是 Integer 类型

### ISSUE THREAD

**Issue by Taskeren** [kaiheila/api-docs#68]
### 如何复现问题?
使用错误的，或不使用 Authorization Header 请求 Gateway。

### 你得到什么结果?
返回的 `code` 为 Integer 类型

### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      |  Java
| 你的操作系统      |  Windows

**Comment by buptlsp** [comment]
已修复，感谢反馈
