### ISSUE TITLE
希望区分 Int32（Integer） 和 Int64（Long）

### ISSUE THREAD

**Issue by Taskeren** [kaiheila/api-docs#69]
### 文档的具体地址?
/

### 你认为有问题的文档内容
全部

### 你期望的结果?
希望区分 Int32（Integer） 和 Int64（Long）

**Comment by Taskeren** [comment]
此外还有别的可以优化的内容：

- 列出 Array 里的类型，例如 Array - Item Type: User 或者直接像 Java 一样 Array<User>
- 和 Array 一样，把 Map 的 Key 和 Value 的类型也列出来
- 将一些特殊的 String 类型返回列出来，比如 UUID，Date

**Comment by buptlsp** [comment]
目前不说明的话，所有的int都是int32
