### ISSUE TITLE
功能建议：开发者模式右键复制角色ID

### ISSUE THREAD

**Issue by KDreamelf** [kaiheila/api-docs#71]
###  功能模块
WIN端，开发者模式
###  你希望的功能描述？
希望新增复制角色ID的能力
### 功能的主要使用产景？
点击按钮或添加回应自动赋予角色，在角色被（其他管理）重建或者新增更多需要自动授予的角色时，需要方便的获取角色ID。（否则需要使用调试工具调用接口获取服务器角色列表再一个个寻找）
### 其它信息
顺便，新版本更新没有推送给`0.0.37.4`，我是手动去官网下载的。

**Comment by buptlsp** [comment]
目前并没有全量更新，角色id问题我需要跟Pm讨论一下

**Comment by Quatrecentquatre-404** [comment]
I tihnk Role ID isn't enough. Being able to copy Roles, Users, Channels, Guilds, Categories and Messages ID would be better.

**Comment by buptlsp** [comment]
![image](https://user-images.githubusercontent.com/3291512/132155691-86276aac-1603-4a5f-8521-ef412de1632b.png)

**Comment by buptlsp** [comment]
you should use the latest version, and open the develop mode, then you can copy role_id, message_id, channel_id and so on

**Comment by Quatrecentquatre-404** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/3291512/132155691-86276aac-1603-4a5f-8521-ef412de1632b.png)

Didn't knew about this button, thanks alot. Things will get easier.
