### ISSUE TITLE
“卡片消息” 中，对于 Card 的作用说明有误

### ISSUE THREAD

**Issue by Misaka-L** [kaiheila/api-docs#84]
### 文档的具体地址?
[卡片消息 - 卡片 - card | https://developer.kaiheila.cn/doc/cardmessage#%E5%8D%A1%E7%89%87](https://developer.kaiheila.cn/doc/cardmessage#%E5%8D%A1%E7%89%87)
### 你认为有问题的文档内容
> ### card
> 作用说明： 标题模块只能支持展示标准文本（text），突出标题样式。
### 你期望的结果?
将其修改为正确的描述

**Comment by fi6** [comment]
已修改，下次pr时合并
