### ISSUE TITLE
无法修改@everyone的频道权限

### ISSUE THREAD

**Issue by zjh4473** [kaiheila/api-docs#99]
### 如何复现问题?
请给出api接口，并给出相应的调用步骤
/api/v3/channel-role/update
传入以下数据
type = role_id
value = "0"
### 你希望的输出是什么?
应该是正常修改@everyone的权限

### 你得到什么结果?
40000, '服务器角色不存在或者你没有权限操作

### 其它信息

| Q                | A
| ---------------- | ---
| 你使用的语言      | python
| 你的操作系统      | windows 和 MacOS

**Comment by buptlsp** [comment]
value=0 肯定是找不到角色的，目前@everyone的修改不是这么改的。。。。
